# Site settings
title: Kisallioppiminen.fi
baseurl: ""
url: "http://kisallioppiminen.github.io"

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from

encoding: UTF-8
sass:
  style: :compressed

navigation:
  "Materiaalit": "/"
  "Blogi": "http://blogs.helsinki.fi/kisallioppiminenlukiossa"
  "Tietoa": "/tietoa.html"

resources:
  css:
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/css/main.css"
  js:
    - "//code.jquery.com/jquery-1.11.0.min.js"
    - "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    - "/js/mooc.js"

exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
