# Site settings
title: Latex-test
baseurl: ""
url: "http://ruumis.github.io/latex-test"

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - with_toc_data
gems:
  - jekyll-redirect-from

sass:
  style: :compressed

navigation:
  "Etusivu": "/"
  "Kurssit": "/kurssit.html"
  "Mik√§ MOOC?": "/mooc.html"
  "In English": "/english.html"

resources:
  css:
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/latex-test/css/main.css"
  js:
    - "//code.jquery.com/jquery-1.11.0.min.js"
    - "//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
    - "/latex-test/js/mooc.js"

exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
